[package]
name = "krkrz_plugin_base"
version = "0.1.0"
edition = "2024"

[dependencies]
krkrz_plugin_base_macros = { path = "./krkrz_plugin_base_macros" }
serde = { version = "1", optional = true }
windows = { version = "0.62", features = ["Win32_System_Com", "docs"], optional = true }

[features]
default = ["com", "serde"]
com = ["dep:windows"]
serde = ["dep:serde"]
unstable = []

[build-dependencies]
bindgen = "0.72"
cc = "1.2"
