[package]
name = "assrender"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
log = "0.4"
krkrz_plugin_base = { path = "../../", default-features = false, features = ["com", "serde"] }
rassa-core = "0.7"
rassa-fonts = "0.7"
rassa-parse = "0.7"
rassa-render = "0.7"
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
